version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y unzip wget python3-boto3 python3-pip
      - wget https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
      - unzip -o terraform_1.1.0_linux_amd64.zip -d /usr/local/bin/
      - pip3 install ansible
  build:
    commands:
      - echo "Applying Terraform..."
      - cd terraform
      - terraform init
      - terraform apply -auto-approve
      - echo "Running Ansible..."
      - cd ../ansible
      - ansible-playbook -i ec2.yml setup.yml
