version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y unzip wget python3-boto3 python3-pip
      - wget https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
      - unzip -o terraform_1.1.0_linux_amd64.zip -d /usr/local/bin/
      - pip3 install ansible
  pre_build:
    commands:
      - echo "Applying Terraform..."
      - cd terraform
      - terraform init
      - terraform apply -auto-approve
  build:
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 400 ~/.ssh/id_rsa
      - ssh-keyscan -H ec2-18.184.5.22.eu-central-1.compute.amazonaws.com >> ~/.ssh/known_hosts
      - echo "Running Ansible..."
      - cd ../ansible
      - ansible-galaxy collection install amazon.aws
      - ansible-playbook setup.yaml -i aws_ec2.yaml
