---
- name: Installiere Apache auf dem Webserver
  hosts: tag_Name_WebServer
  become: yes
  tasks:
    - name: Aktualisiere APT-Paketliste
      apt:
        update_cache: yes
    - name: Installiere Apache
      apt:
        name: apache2
        state: present
    - name: Starte Apache
      service:
        name: apache2
        state: started
